# Generated by Django 4.0.4 on 2022-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='chisqr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
